name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Extract version
        id: version
        run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}

      - name: Build and tag Docker image
        run: |
          docker build -t ghcr.io/bdcomputing/dental-api:$VERSION .
          docker tag ghcr.io/bdcomputing/dental-api:$VERSION  ghcr.io/bdcomputing/dental-api:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/bdcomputing/dental-api:$VERSION
          docker push ghcr.io/bdcomputing/dental-api:latest
