name: Create a new release on pushed tag

on:
  push:
    tags:
      - '*'
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Create a new release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$GITHUB_REF_NAME" \
              --repo="$GITHUB_REPOSITORY" \
              --title="v${tag#v}" \
              --generate-notes
  publish-docker-image:
    name: Build and Publish Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Extract version
        id: version
        run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}

      - name: Build and tag Docker image
        run: |
          docker build -t ghcr.io/bdcomputing/zaito-invoicing-api:$VERSION .
          docker tag ghcr.io/bdcomputing/zaito-invoicing-api:$VERSION  ghcr.io/bdcomputing/zaito-invoicing-api:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/bdcomputing/zaito-invoicing-api:$VERSION
          docker push ghcr.io/bdcomputing/zaito-invoicing-api:latest
